In [2]:
import numpy as np
import pandas as pd

In [13]:
df1 = pd.DataFrame({'c1' : np.arange(5),
            'c2' : np.random.randn(5)},
            index = ['r0','r1','r2','r3','r4'])

In [16]:
df1.reindex(['r0','r1','r2','r5','r6'], fill_value='missing')

c1        c2
r0        0  -2.17369
r1        1  0.983588
r2        2  -3.14473
r5  missing   missing
r6  missing   missing

In [17]:
## 데이터 프레임 합치기 ##

In [18]:
# concat: 축을 따라 데이터프레임을 합침
# merge: 하나 이상의 키를 기준으로 데이터프레임의 로우를 합침
'''
axis = 0  -> 위/아래로 합침
join = 'inner' or 'outer'  / outer: 합집합, inner: 교집합
ignore_index = False(True: 기존 index 무시)
names = index 이름 부여
'''

"\naxis = 0  -> 위/아래로 합침\njoin = 'inner' or 'outer'  / outer: 합집합, inner: 교집합\nignore_index = False(True: 기존 index 무시)\nnames = index 이름 부여\n"

In [24]:
df1 = pd.DataFrame({
    'A' : ['A0','A1','A2'],
    'B' : ['B0','B1','B2'],
    'C' : ['C0','C1','C2'],
    'D' : ['D0','D1','D2']
})

In [25]:
df2 = pd.DataFrame({
    'A' : ['A3','A4','A5'],
    'B' : ['B3','B4','B5'],
    'C' : ['C3','C4','C4'],
    'D' : ['D3','D4','D5']
},
index = [3, 4, 5])

In [27]:
pd.concat([df1, df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C4  D5

In [28]:
df3 = pd.DataFrame({'E': ['A6', 'A7', 'A8'],
    'F': ['B6', 'B7', 'B8'],
    'G': ['C6', 'C7', 'C8'],
    'H': ['D6', 'D7', 'D8']},
    index=[0, 1, 2])

In [29]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [30]:
df3

E   F   G   H
0  A6  B6  C6  D6
1  A7  B7  C7  D7
2  A8  B8  C8  D8

In [32]:
pd.concat([df1,df3],axis=1)

A   B   C   D   E   F   G   H
0  A0  B0  C0  D0  A6  B6  C6  D6
1  A1  B1  C1  D1  A7  B7  C7  D7
2  A2  B2  C2  D2  A8  B8  C8  D8

In [33]:
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'E': ['E0', 'E1', 'E2']},
     index=[0, 1, 3])


In [34]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [36]:
df4

A   B   C   E
0  A0  B0  C0  E0
1  A1  B1  C1  E1
3  A2  B2  C2  E2

In [43]:
pd.concat([df1, df4], join='outer')

A   B   C    D    E
0  A0  B0  C0   D0  NaN
1  A1  B1  C1   D1  NaN
2  A2  B2  C2   D2  NaN
0  A0  B0  C0  NaN   E0
1  A1  B1  C1  NaN   E1
3  A2  B2  C2  NaN   E2

In [44]:
pd.concat([df1, df4],axis = 1, join='outer')

A    B    C    D    A    B    C    E
0   A0   B0   C0   D0   A0   B0   C0   E0
1   A1   B1   C1   D1   A1   B1   C1   E1
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN   A2   B2   C2   E2

In [45]:
pd.concat([df1, df4],axis = 1, join='inner')

A   B   C   D   A   B   C   E
0  A0  B0  C0  D0  A0  B0  C0  E0
1  A1  B1  C1  D1  A1  B1  C1  E1

In [46]:
pd.concat([df1, df4], axis = 1)

A    B    C    D    A    B    C    E
0   A0   B0   C0   D0   A0   B0   C0   E0
1   A1   B1   C1   D1   A1   B1   C1   E1
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN   A2   B2   C2   E2

In [47]:
df5 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'D': ['D0', 'D1', 'D2']},
     index=['r0', 'r1', 'r2'])


df6 = pd.DataFrame({'A': ['A3', 'A4', 'A5'],
     'B': ['B3', 'B4', 'B5'],
     'C': ['C3', 'C4', 'C5'],
     'D': ['D3', 'D4', 'D5']},
     index=['r3', 'r4', 'r5'])


In [51]:
pd.concat([df5, df6], axis = 0, ignore_index=False)

A   B   C   D
r0  A0  B0  C0  D0
r1  A1  B1  C1  D1
r2  A2  B2  C2  D2
r3  A3  B3  C3  D3
r4  A4  B4  C4  D4
r5  A5  B5  C5  D5

In [52]:
pd.concat([df5, df6], axis = 0, ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [57]:
df56_with_keys = pd.concat([df5, df6], keys=['df5', 'df6'])
df56_with_keys

A   B   C   D
df5 r0  A0  B0  C0  D0
    r1  A1  B1  C1  D1
    r2  A2  B2  C2  D2
df6 r3  A3  B3  C3  D3
    r4  A4  B4  C4  D4
    r5  A5  B5  C5  D5

In [60]:
df56_with_keys.loc['df5'].loc['r1']

A    A1
B    B1
C    C1
D    D1
Name: r1, dtype: object

In [62]:
pd.Series(['S1','S2','S3'], name = 'S')
pd.Series(['S1','S2','S3'], name = 'S',
         index = ['c','d','e'])

c    S1
d    S2
e    S3
Name: S, dtype: object

In [63]:
s1 = pd.Series(['S1','S2','S3'], name = 'S')

In [64]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [65]:
s1

0    S1
1    S2
2    S3
Name: S, dtype: object

In [67]:
pd.concat([df1,s1],axis = 1, ignore_index=True)

0   1   2   3   4
0  A0  B0  C0  D0  S1
1  A1  B1  C1  D1  S2
2  A2  B2  C2  D2  S3

In [68]:
s2 = pd.Series([0,1,2])
s3 = pd.Series([3,4,5])

In [70]:
pd.concat([s1,s2], axis = 1)

S  0
0  S1  0
1  S2  1
2  S3  2

In [75]:
s4 = pd.Series(['S1','S2','S3','S4'], index=['A','B','C','E'])

In [76]:
df1.append(s4,ignore_index=True)

A   B   C    D    E
0  A0  B0  C0   D0  NaN
1  A1  B1  C1   D1  NaN
2  A2  B2  C2   D2  NaN
3  S1  S2  S3  NaN   S4

In [80]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
arr+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [82]:
arr+arr

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [85]:
# 배열 간 합치기 작업
np.concatenate([arr,arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
np.concatenate([arr,arr],axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [94]:
s1 = pd.Series([0,1], index=['a','b'])
s2 = pd.Series([2,3,4], index=['c','d','e'])
s3 = pd.Series([5,6], index=['f','g'])
pd.concat([s1,s2,s3],axis = 1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [95]:
s1+5

a    5
b    6
dtype: int64

In [100]:
s4 = pd.concat([s1*5,s3])

In [101]:
pd.concat([s1,s4],axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [102]:
pd.concat([s1,s4],axis=1,join = 'inner')

0  1
a  0  0
b  1  5

In [104]:
pd.concat([s1,s1,s3],axis = 0)

a    0
b    1
a    0
b    1
f    5
g    6
dtype: int64

In [106]:
res = pd.concat([s1,s1,s3],keys = ['one','two','three'])
res

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [107]:
res.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0