# Numpy
```python
import numpy as np
```
- Numerical Python
- 과학 계산을 위한 패키지
- 다차원 배열을 기존 자료구조로 한다(n-Dimension array = ndarray)
- 브로드캐스팅 기능 지원(그림자 분신술? / 자동으로 데이터에 shape을 연산이 가능한 형태로 확장해줌.)
- 기존 파이썬에서는 반복문 작성을 통해 연산을 했지만, 
  Numpy에서는 반복문 없이 연산 가능 >> 매우 빠른 연산 가능!
- 기본적인 선형대수 중요함(2~3일) >> Numpy에서 지원,
  난수 생성기 포함(난수: 컴퓨터에서 발생하는 임의의 수, random number)
  푸리에 변환(Fourier)
- C언어와 연결 가능.
- 벡터에서 데이터 가공, 정제, 필터링(boolean), 변형 연산을 빠르게 할 수 있도록 지원
- 정렬, 데이터 검색, 집합단위 연산, 통계, 데이터 요약
- 병합, 관계 표현

- Numpy는 대용량 배열을 효율적으로 처리할 수 있도록 설계됨.

In [1]:
# 수치연산을 위한 넘파이
# 데이터 분석을 위한 판다스
# ++ 시각화!
# ==>> 리포트 작성 가능.

# 산출물 관리 잘하자!


In [21]:
import numpy as np
myArr = np.arange(1000000) # arange: 메서드  /  arange라는 메서드는 numpy가 가지고 있음. 자료구조가 array
myList = list(range(1000000)) # range는 파이썬이 가지고있는 기본적인 함수. 자료구조가 list
myArr*2  # 브로드캐스팅: 

%time for _ in range(30): myArr = myArr*2
# 61ms
myList2 = [i*2 for i in myList]
myList2

%time for _ in range(30): myList2 = [i*2 for i in myList]
# 2.22s

# 넘파이가 훨~씬 계산 속도가 빠르다!!

Wall time: 61 ms
Wall time: 2.22 s


In [29]:
data = np.random.randn(2,3) # random normal distribution 
# 표준정규분포: 평균 0 / 표준편차 1
data*10
data + data
data.shape # 행렬 구성 확인  (2,3)  ==> 2행 3열
data.dtype # 자료형 타입 확인  float64

dtype('float64')

In [50]:
data1 = [1, 1.5, 2, 0]
arr1 = np.array(data1)
arr1
# array([1. , 1.5, 2. , 0. ]) 숫자 뒤에 점이 다 붙어 있음. (float)
# array할 때 자동으로 적절한 자료형을 유추한다.
data2 = [[1,2,3,],[4,5,6]]
arr2 = np.array(data2)
arr2.ndim # 몇차원이냐?
arr2.shape
arr1.dtype
arr2.dtype  # dtype: data type 확인!
np.zeros(10)  # 0이 10개인 array
np.zeros((3,6))  # 3행 6열 array
np.zeros((2,3,4))  # 1행에 요소 4개, 1행이 3개, 1행 3개가 2개.
arr1 = np.array([1,2,3], dtype = np.float64)  # 데이터의 의미(데이터의 데이터 == 메타데이터)
arr1

arr2 = np.array([1,2,3], dtype = np.int32)  # 데이터의 의미(데이터의 데이터 == 메타데이터)
arr2.dtype

dtype('int32')

#### @numpy
- int32: 32비트 정수형(4byte)
  int64: 64비트(8byte)
- float: 실수형
- bool: 논리형(True나 False)
- object: 객체
- string: 문자열
- astype 메서드: dtype을 다른 형식으로 변환(캐스팅)할 때 사용하는 메서드




In [73]:
# 정수 -> 실수 변환
arr = np.array([1,2,3])
floatArr = arr.astype(np.float64)

# 실수 -> 정수 변환
arr = np.array([1.2, -2.5, 3.1])
intArr = arr.astype(np.int32)
intArr
arr = np.array(['1.5','-2.7','30'])
arr  # array(['1.5', '-2.7', '30'], dtype='<U4')  unicode를 의미함.
arr.astype(float)
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr * arr  # 벡터화 연산
1/arr
arr2 = np.array([[0,1,2],[7,8,9]])
arr > arr2



array([[ True,  True,  True],
       [False, False, False]])

#### 브로드캐스팅: 크기가 다른 배열간의 연산
흠 어떻게 하는거징


In [88]:
arr = np.arange(10)
arr[5]
arr[5:8] = 12
arrslice = arr[5:8]
arrslice[1] = 999
arrslice
arr
# 따와서 변경시켜도 원본에 적용됨.
# arr이라는 원본에서부터 만들어진 사본 arrslice에서 바꿔도 원본이 바뀜.


array([  0,   1,   2,   3,   4,  12, 999,  12,   8,   9])

In [103]:
arrslice[0] = 100
arr # 원래 파이썬이랑 달라서 헷갈릴 수 있음!!
arrslice[:] = 777
arrslice  # array([777, 777, 777])
arr  # array([  0,   1,   2,   3,   4, 777, 777, 777,   8,   9])
arrslice2 = arr[5:8].copy()
arrslice2[0] = 333
arrslice2
arr  # copy를 하면 원래 arr와 연결되지 않는다!!
# copy를 안쓰고 참조해서 특정값을 바꾸면 원본또한 바뀌게 되는데,
# copy를 쓴다면 원본과는 상관없다.
# copy를 하면 메모리가 따로 할당이 됨. 
# 안하고 참조한다면 메모리는 하나에 할당이되고 경로를 공유? 함. 이런 느낌.

array([  0,   1,   2,   3,   4, 777, 777, 777,   8,   9])

In [111]:
arr2 = np.array([[1,2],[3,4],[5,6]])
arr2[2]  # 1차원 배열이 참조됨.
         # 2차원 배열[인덱스]  -> 1차원 배열이 참조됨.
         # 만약 5차원 배열[인덱스]  -> 4차원 배열이 참조됨.
arr2[2][0]
arr2[2,0]

5

In [130]:
arr = np.array(list(range(1,25)))
arr #(2,3,4)의 array로 변경해볼까?
arr3d = arr.reshape(2,3,4)
arr3d  # 2*3*4 크기의 배열
arr3d[0]  # 3*4 크기의 배열
arr3d[0][0]  # 1*4 크기의 배열
oldValues = arr3d[0].copy()
arr3d[0] = 99
arr3d
arr3d[0] = oldValues
arr3d


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [138]:
arr3d[1][2][3] # == arr3d[1, 2, 3]
arr3d[-1][-2][-2]

19

In [142]:
arr
arr[1:10]
arr = arr.reshape(6,4)
arr[-2]

array([17, 18, 19, 20])

In [152]:
a = [1,3,5]
b = []
for i in range(len(a)-1,-1,-1):
    b.extend([a[i]])
b


[5, 3, 1]

In [155]:
for i in reversed(range(len(a))):
    print(a[i])

5
3
1


In [158]:
for i in reversed(a):
    print(i)


5
3
1


In [164]:
arr3d[0][:2]
arr3d[1][:1,2:] = 77
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 77, 77],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])