In [49]:
import pandas as pd
data = pd.read_csv('Cancer_data.csv')

In [50]:
data.isnull().sum()
data.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [51]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [52]:
xdata = data.iloc[:,2:32].values
xdata

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [53]:
ydata = data.iloc[:,1].values
ydata

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'M',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M

In [54]:
le = LabelEncoder()
ydata = le.fit_transform(ydata)
ydata

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [55]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(xdata,ydata,test_size = 0.25, random_state = 0)

In [56]:
# scaling
from sklearn.preprocessing import StandardScaler

In [57]:
sc = StandardScaler()
xTrain = sc.fit_transform(xTrain)
xTest = sc.fit_transform(xTest)

In [58]:
xTrain

array([[-0.65079907, -0.43057322, -0.68024847, ..., -0.36433881,
         0.32349851, -0.7578486 ],
       [-0.82835341,  0.15226547, -0.82773762, ..., -1.45036679,
         0.62563098, -1.03071387],
       [ 1.68277234,  2.18977235,  1.60009756, ...,  0.72504581,
        -0.51329768, -0.96601386],
       ...,
       [-1.33114223, -0.22172269, -1.3242844 , ..., -0.98806491,
        -0.69995543, -0.12266325],
       [-1.25110186, -0.24600763, -1.28700242, ..., -1.75887319,
        -1.56206114, -1.00989735],
       [-0.74662205,  1.14066273, -0.72203706, ..., -0.2860679 ,
        -1.24094654,  0.2126516 ]])

In [59]:
xTest

array([[-0.1839902 ,  0.22170989, -0.11761404, ...,  1.40089716,
         1.16977773,  1.37108056],
       [-0.23927557,  1.20953909, -0.30776593, ..., -0.79588429,
        -0.81775175, -0.91991041],
       [-0.00358531, -0.79326895, -0.07782455, ..., -0.46102846,
        -1.35426278, -0.9614486 ],
       ...,
       [-0.49242436, -1.50124802, -0.52388569, ..., -0.0848268 ,
         0.34236625, -0.49174753],
       [-0.14616337, -1.77900972, -0.14818913, ..., -0.58355147,
        -0.35440132, -0.70529643],
       [ 1.61714893, -0.27324893,  1.6440133 , ...,  1.69773906,
         1.27080903,  0.37682669]])

In [60]:
from sklearn.ensemble import RandomForestClassifier

In [61]:
rfModel = RandomForestClassifier(n_estimators=10, criterion='entropy',random_state=0)

In [62]:
rfModel.fit(xTrain,yTrain)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [63]:
yPred = rfModel.predict(xTest)

In [64]:
# 
from sklearn.metrics import confusion_matrix, accuracy_score

In [65]:
cm = confusion_matrix(yTest, yPred)
cm
#            암 예측     not 암 예측
# 실제 암      [88(TP),  2(FN)],
# 실제 not암   [ 1(FP), 52(TN)]

# TP: 암을 암이라고 예측
# TN: 암이 아닌것을 아니라고 정확하게 예측
# FP: 암을 암이 아니라고 예측
# FN: 암이 아닌 것을 암이라고 잘못 예측

# Cancer: 양성(positive), 음성(negative)
# Tumor: 양성(benign), 악성(malignat)

array([[88,  2],
       [ 1, 52]], dtype=int64)

In [66]:
accuracy_score(yTest, yPred)

0.9790209790209791

In [67]:
# 일반적으로 알고리즘은 문자형 데이터 인식을 못함 -> 숫자로 바꿔줘야해!
# Encoding 종류
# 레이블, 원핫
# 레이블: 문자형 데이터가 수치로 변환되었을 때 연산, 크기 비교가 가능한 데이터 형태일 때(학점)
# 원 핫: 연산, 크기 비교가 안되는 데이터(서울, 대전, 대구, 부산, ...)
#        서울(1) + 대전(2) = 대구(3)????? 말이 안되거든..
#       서울: 10000, 대전: 01000, 대구: 00100 ...

In [68]:
# 레이블 인코딩은 선형회귀와 같은 알고리즘에 적용하면 안됨!
from sklearn.preprocessing import LabelEncoder

In [69]:
items = ['tv','냉장고','에어컨','에어컨','전자렌지','tv']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 2, 2, 3, 0], dtype=int64)

In [70]:
# 원 데이터 출력
encoder.inverse_transform(labels)

array(['tv', '냉장고', '에어컨', '에어컨', '전자렌지', 'tv'], dtype='<U4')

In [71]:
# 중복 제외 데이터 종류
encoder.classes_

array(['tv', '냉장고', '에어컨', '전자렌지'], dtype='<U4')

In [72]:
# OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

# 1) 모든 문자열의 값을 숫자로 변환
items = ['tv','냉장고','에어컨','에어컨','전자렌지','tv']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

# 2) 숫자로 변환된 데이터(2차원)에 대해 OneHotEnoder 진행!
labels = labels.reshape(-1,1)
ohe = OneHotEncoder()
ohe.fit(labels)
oh_labels = ohe.transform(labels)
# oh_labels가 sparse matrix이기 때문에 array로 타입 변경
print(oh_labels.toarray())

df = pd.DataFrame(items,columns=['items'])
pd.get_dummies(df)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


items_tv  items_냉장고  items_에어컨  items_전자렌지
0         1          0          0           0
1         0          1          0           0
2         0          0          1           0
3         0          0          1           0
4         0          0          0           1
5         1          0          0           0

In [73]:
# decision tree에서는 scaling 안해도 돼! 자기가 알아서 Entropy 계산 해서 IG가 가장 큰 값을 찾는 거징.
# 변수의 scaling(표준화, 정규화)을 하지 않아도 됨!(@Decision Tree)
# scaling 언제?? ->  Regression, deeplearning, 할땐 무조건! (값의 편향을 막기 위해)
# criteion : gini(default), entropy


In [74]:
# train -> Decision Tree -> train입력 -> 모델 평가(성능 100%)  =>  편협적인 모델(가지치기를 안함!) 
# => 결국 성능이 떨어짐...
# train 입력 -> 모델평가 (95%) // test 입력 -> 모델평가 (93%)  => 오버피팅인데 용서되는 경우
# train 입력 -> 모델평가 (95%) // test 입력 -> 모델평가 (70%)  
#                                             => 오버피팅!!! (일반화(가지치기)를 제대로 하지 않아서...)