https://numpy.org/doc/    <<--- 이거 항상 공부
- NumPy 의 버전을 항상 확인해볼 필요가 있다.

In [1]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

In [9]:
z=np.zeros((10,10))
z.size # 요소 개수 10*10 = 100개
z.itemsize # 8바이트
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [12]:
z=np.arange(10)
z
z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
np.nonzero([1,2,0,0,3]) #0이 아닌 index를 알려줌 (가끔 사용할 일이 있다.)

(array([0, 1, 4], dtype=int64),)

In [20]:
z=np.random.random((10,10))
zmin,zmax=z.min(), z.max()
print(zmin, zmax)
z.mean()

0.013873506529568536 0.9830191089384629


0.4916550432607923

In [25]:
# 10*10 배열 생성
# 테두리는 모드 1 내부는 모두0으로 채우세요

l=np.zeros((10,10))
l

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
ans=np.ones((10,10))

In [44]:
ans[1:-1, 1:-1]=0

In [45]:
ans

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
#padding() -> 패딩 = 배열의 크기를 고정길이로 만드는 작업
a=[1,2,3] 
np.pad(a,1,constant_values=0) #(배열, 크기)   좌우에 0이 채워짐
np.pad(a, (2,3), constant_values=0) # 좌 2개, 우 3개 0으로 채워짐
np.pad(a, (0,3), constant_values=0) # 우 3개 0으로 채워짐
b=np.arange(1,7).reshape(2,3)
print(b)
np.pad(b, pad_width=1, constant_values=0) #pad_width 는 디폴트로 들어가 있어서 없어도 되지만 가독성을 위해 추가
np.pad(b, pad_width=3, constant_values=0)
np.pad(b, ((1,1),(2,2)), constant_values=0)
#         ((상,하),(좌,우))
#이미지 처리할때 패딩을 많이 사용한다. CNN 알고리즘을 처리할때 이미지에대한 특성을 사용할때 크기가 줄어들면,
#패딩읕 통해서 원본 이미지 사이즈를 유지하는데 용이함
np.pad(b, ((1,2),(3,4)), constant_values=0)

[[1 2 3]
 [4 5 6]]


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [68]:
c=[
    [1,2],
    [4,5,6],
    [7]
] #이런 열이 맞지 않는 2차원 배열이 있다고 가정
print(c)
np.array(c) #list -> array     dtype = object    padding을 사용하여 고쳐보자

[[1, 2], [4, 5, 6], [7]]


array([list([1, 2]), list([4, 5, 6]), list([7])], dtype=object)

In [84]:
#************ 모든 행의 길이가 5로 일정하게 통일 *************
def twoDArray(c, fixedLength, paddingValue):
    rows=[]
    for a in c:
#         print(a)
        rows.append(np.pad(a,(0,fixedLength), constant_values=paddingValue)[:fixedLength]   ) #(0,3), constant_values=0) # 우 3개 0으로 채워짐 처럼 : 왼쪽은 0개 오른쪽은 5개 밑에 정의 된것처럼
                 #(np.pad(a,(0,fixedLength), constant_values=paddingValue) <- 배열이니까  [:fixedLength] 로 왼쪽부터 5개 지정가능!
#     print(rows)
    return np.concatenate(rows, axis=0).reshape(-1,fixedLength)     #concatenate 함수로 합칠수 있다. reshape(-1,fixedLength)=행의 갯수는 모르겠어 근데 열은 알때
    
twoDArray(c, fixedLength=5, paddingValue=0)

array([[1, 2, 0, 0, 0],
       [4, 5, 6, 0, 0],
       [7, 0, 0, 0, 0]])

In [91]:
# 바깥 테두리가 0, 내부는 1 의 10*10 행렬
z=np.zeros((10,10))
z[1:-1,1:-1]=1
z



array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [100]:
a=np.ones((8,8))
np.pad(a,((1,1),(1,1)),constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [102]:
# 훨씬 가독성 좋고 옳은 답!
b=np.ones((10,10))
np.pad(a,((1,1),(1,1)),constant_values=0)[:10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

- 대각행렬: 대각성분을 제외한 모든 성분이 0인 정방행렬

In [110]:
x=np.arange(9).reshape(3,3)
print(x)
print('='*10)
print(np.diag(x))
print('='*10)
print(np.diag(np.diag(x))) #대각행렬을 만들어라 : 대각성분을 제외한 나머지가 0

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [111]:
np.diag([3,2,0])

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 0]])

In [125]:
a=np.arange(1,7)
a
row_vector=a[np.newaxis, :]
col_vector=a[: ,np.newaxis]
print(row_vector)
print(col_vector)

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [133]:
#타일 : 붙여넣기 편리함
a=np.array([0,1,2])
a
np.tile(a,2)
np.tile(a,(4,1))
np.tile(a,(4,3))

"""
01010101
10101010
01010101
10101010
01010101
10101010
01010101
10101010
타일 함수이용해서 만들기
"""


array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [156]:
# 타일함수를 안사용한경우
z=np.zeros((8,8), dtype=int)
z[1::2, ::2]=1 #2칸씩, 맨앞에서부터 마지막까지 2칸씩 띄기
z
z[::2, 1::2]=1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [157]:
# 타일함수를 사용한경우
z=np.array([[0,1],[1,0]])
np.tile(z,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 표준화/정규화

In [158]:
#표준화
z=np.random.random((5,4))
z

array([[0.25057309, 0.66072901, 0.33925029, 0.69834013],
       [0.04486815, 0.09726056, 0.60604392, 0.60732259],
       [0.14012456, 0.29486438, 0.35589253, 0.88949873],
       [0.67022606, 0.97026385, 0.44411507, 0.25853165],
       [0.73406955, 0.31499772, 0.4754062 , 0.83297478]])

In [161]:
print(np.mean(z)) #전체 평균
print(np.mean(z,axis=0)) #열단위 평균
print(np.mean(z,axis=1)) #행단위 평균
print(np.std(z)) #표준편차,

0.4842676414984098
[0.36797228 0.4676231  0.4441416  0.65733358]
[0.48722313 0.33887381 0.42009505 0.58578416 0.58936206]
0.264244013082464


In [164]:
(z-np.mean(z))/np.std(z) #standardization : 표준화 = 평가도구의 규준(norms)을 설정하는 작업으로, 검사를 시행하기 위한 절차 혹은 조건이 일관성이나 동일성을 갖추도록 하는 것. 
#(전체 각 데이터-전체 데이터 평균)/전체 표준편차
#(각 열 데이터 - 각 열 데이터 평균)/ 각 열 데이터 표준편차   <-- 올바른 의미
#각 열 데이터 표준화

# 토익 토플 수능 국어
# 900  800  400 100
# 위에 것들을 전처리를 해야 모델이 엉망으로 안나온다.

array([[-0.8843892 ,  0.66779702, -0.54880089,  0.81013186],
       [-1.66285504, -1.4645822 ,  0.46084782,  0.46568681],
       [-1.3023685 , -0.7167741 , -0.48582034,  1.5335488 ],
       [ 0.70373749,  1.83919479, -0.15195264, -0.85427099],
       [ 0.94534558, -0.64058184, -0.03353507,  1.31964065]])

In [165]:
z=np.arange(10,30).reshape(4,5)
print(z)
#z 를 각 열 데이터 단위로 표준화 = (각열 데이터-열 데이터 평균)/열 데이터 표준편차
#z 를 각 열 데이터 단위로 정규화 = (각열 데이터 -열 최소값)/열 최대값 - 열 최소값

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [198]:
#표준화
c=np.mean(z, axis=0) #열 데이터 평균 array([17.5, 18.5, 19.5, 20.5, 21.5])
s=np.std(z, axis=0) #열 데이터 표준편차 array([5.59016994, 5.59016994, 5.59016994, 5.59016994, 5.59016994])
z0=z[0:,0] # 각열 데이터
z1=z[0:,1]
z2=z[0:,2]
z3=z[0:,3]
z4=z[0:,4]
s0=(z0-c[0])/s[0]
s1=(z1-c[1])/s[1]
s2=(z2-c[2])/s[2]
s3=(z3-c[3])/s[3]
s4=(z4-c[4])/s[4]
np.array([s0,s1,s2,s3,s4])

array([[-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079],
       [-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079],
       [-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079],
       [-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079],
       [-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079]])

In [ ]:
# normalization:정규화 = 데이터를 일정한 규칙에 따라 변형하여 이용하기 쉽게 만드는 일