In [1]:
import numpy as np

문제 1. 길이가 10인 0-벡터를 만드세요.

In [2]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

문제 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [3]:
arr = np.array([0]*10)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

문제 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [4]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

문제 4. 위 벡터의 순서를 바꾸세요.

In [5]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

문제 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [6]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

문제 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [7]:
arr = np.array([1,2,0,0,4,0])
arr[np.where(arr!=0)]

array([1, 2, 4])

문제 7. 3x3 단위 행렬(identity matrix)을 만드세요

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

문제 8. 난수 원소를 가지는 3x3 행렬을 만드세요

In [9]:
arr = np.random.randn(3, 3)
arr

array([[-0.30295637,  0.73693026, -0.41887448],
       [-0.61230699, -0.90655308,  0.96465354],
       [ 0.55393623,  1.02480811,  1.06303799]])

문제 9. 위에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [10]:
print("최대값 : ", arr.min())
print("최소값 : ", arr.max())

최대값 :  -0.9065530835957257
최소값 :  1.0630379873570281


문제 10. 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [11]:
print("행 평균 : ", arr.mean(axis=1))
print("열 평균 : ", arr.mean(axis=0))

행 평균 :  [ 0.00503314 -0.18473551  0.88059411]
열 평균 :  [-0.12044237  0.28506176  0.53627235]
