In [ ]:
x if 조건
>> 조건이 맞으면 x를 실행

x if 조건 else y
>> 조건이 맞으면 x를 실행, 틀리면 y를 실행

In [1]:
import numpy as np

In [4]:
# np.where함수 == x if 조건 else y
# 참이면 xarr의 값, 거짓이면 yarr의 값.
xarr = np.array([1,2,3,4,5])
yarr = np.array([2,3,4,5,6])
cond = np.array([True, False, True, True, False])

res = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
# 파이썬으로 수행 -> 큰 배열이라면 매우 속도가 늦음.
res

[1, 3, 3, 4, 6]

In [8]:
# np.where(조건, 참일 경우, 거짓인 경우)
res = np.where(cond, xarr, yarr) # 매우 빠르고 간결하게 수행 가능.
res

array([1, 3, 3, 4, 6])

In [16]:
arr = np.random.randn(4,4)
# arr에 저장된 값이 0 초과이면 값을 2로, 0 이하이면 0으로 변경

np.where(arr>0, 2, 0)

array([[2, 0, 2, 2],
       [2, 2, 2, 0],
       [0, 2, 2, 0],
       [0, 0, 2, 0]])

In [21]:
# arr값이 0보다 크면 2로, 그렇지 않으면 arr값 그대로.
np.where(arr>0, 2, arr)

array([[ 2.        , -1.40343899,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.680673  ],
       [-0.5535846 ,  2.        ,  2.        , -1.41051784],
       [-0.61643931, -0.61577817,  2.        , -0.25856932]])

In [46]:
# 수학, 통계 메서드(합, 평균, 표준편차, 분산, 공분산 등)
arr = np.random.randn(5,4)

In [52]:
arr.mean() # 평균
np.mean(arr) # 평균
arr.sum() # 합
np.sum(arr) # 합

-1.7305862206490923

In [56]:
# axis = 1 -> 같은 행 // axis = 0 -> 같은 열
arr.mean(axis = 1) # 같은 행에 위치한 데이터 평균
arr.mean(axis = 0) # 같은 열에 위치한 데이터 평균
arr.sum(axis = 1)

array([-0.76461315, -0.92133008, -2.00209772,  2.51351936, -0.55606463])

In [60]:
arr = np.arange(8) # 1차원 array: 0~7 
arr.cumsum() # 누적합

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [68]:
# 0~8까지 값으로 초기화해서 배열 생성, 3*3
arr = np.arange(9).reshape(3,3)  # 배열 재생성 -> reshape
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
arr.cumsum()  # array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)
arr.cumsum(axis = 0) # array([[ 0,  1,  2],
                            # [ 3,  5,  7],
                           # [ 9, 12, 15]], dtype=int32)
arr.cumsum(axis = 1)# array([[ 0,  1,  3],
                            # [ 3,  7, 12],
                           # [ 6, 13, 21]], dtype=int32)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [73]:
arr.cumprod(axis = 1)  # prod: 곱  / cumprod: 누적곱

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [81]:
# boolean 배열 메서드
arr = np.random.randn(100)  # 표준정규분포에서 난수 발생 -> 평균 ~= 0 / 표준편차 ~= 1
(arr > 0).sum()  # False: 0  // True: 1로 취급해서 sum 실행.
bools = np.array([False, False, True, False])
bools.any() # 하나 이상의 값이 True이기만 하면 전체가 True가 됨.
bools.all() # 모든 요소의 값이 Ture일 때만 전체가 True가 됨.

False

In [83]:
arr = np.random.randn(6)
arr.sort()

In [84]:
arr

array([-0.36216073, -0.19274957,  0.01722982,  0.9431703 ,  1.44038255,
        1.59311372])

In [91]:
arr = np.random.randn(5,3)
arr

array([[-1.3200874 , -0.72992399, -2.0163709 ],
       [-1.0333009 , -0.81252272,  0.16940401],
       [ 1.92937347, -0.94077602, -1.2263208 ],
       [-2.71704605, -0.55186654, -1.28535841],
       [-0.40578247, -0.21817252,  0.1249071 ]])

In [92]:
arr.sort()  # 행 단위로 sort가 됨.
arr

array([[-2.0163709 , -1.3200874 , -0.72992399],
       [-1.0333009 , -0.81252272,  0.16940401],
       [-1.2263208 , -0.94077602,  1.92937347],
       [-2.71704605, -1.28535841, -0.55186654],
       [-0.40578247, -0.21817252,  0.1249071 ]])

In [94]:
arr.sort(0)  # 열 단위로 sort가 됨.
arr

array([[-2.71704605, -1.3200874 , -0.72992399],
       [-2.0163709 , -1.28535841, -0.55186654],
       [-1.2263208 , -0.94077602,  0.1249071 ],
       [-1.0333009 , -0.81252272,  0.16940401],
       [-0.40578247, -0.21817252,  1.92937347]])

In [96]:
arr.sort(1)  # 배열에 대한 sort라서 python에서 sort와 numpy에서 sort는 다르다.
arr

# 배열.sort(): 원래 배열 자체를 정렬함.
# np.sort(): 원래의 배열은 그대로 둔 채 정렬된 결과를 복사본으로 리턴

array([[-2.71704605, -1.3200874 , -0.72992399],
       [-2.0163709 , -1.28535841, -0.55186654],
       [-1.2263208 , -0.94077602,  0.1249071 ],
       [-1.0333009 , -0.81252272,  0.16940401],
       [-0.40578247, -0.21817252,  1.92937347]])

In [100]:
x = np.array([3,2,5,4,1,9,0])
x.sort() # 배열 자체를 정렬함.
x

array([0, 1, 2, 3, 4, 5, 9])

In [118]:
x = np.array([3,2,5,4,1,9,0])
np.sort(x)


array([0, 1, 2, 3, 4, 5, 9])

In [119]:
x

array([3, 2, 5, 4, 1, 9, 0])

In [124]:
np.sort(x)[::-1] # 맨 뒤에서부터 뒤로 한 칸씩 출력.


array([9, 5, 4, 3, 2, 1, 0])

In [125]:
np.sort(x)[:]  # 그냥 전체 출력


array([0, 1, 2, 3, 4, 5, 9])

In [126]:
np.sort(x)[::2]  # 한 칸 건너 한칸 출력

array([0, 2, 4, 9])

In [128]:
x = np.array([3,2,5,4,1,9,0])  # 0 1 2 3 4 5 9
                        # index  6 4 1 0 3 2 5
np.argsort(x)
# array([6, 4, 1, 0, 3, 2, 5], dtype=int64)
# x에 저장되어있는 데이터를 오름 차순 정렬했을 때 그 결과에 대한 원 데이터의index.


array([6, 4, 1, 0, 3, 2, 5], dtype=int64)

In [132]:
np.argsort(-x) # 내림차순 정렬했을 때 그 결과에 대한 원 데이터의 index.
# 9 5 4 3 2 1 0
# 5 2 3 0 1 4 6

array([5, 2, 3, 0, 1, 4, 6], dtype=int64)

In [134]:
x[np.argsort(-x)] # 내림차순 정렬

array([9, 5, 4, 3, 2, 1, 0])

In [138]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
np.sort(x,axis = 1) # 행 단위 오름차순

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
np.sort(x,axis = 0) # 열 단위 오름차순 (axis 생략 가능)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
np.sort(x,axis = 1)[::-1] # 열 축을 기준으로 거꾸로 출력

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [150]:
x = np.array([[2,1,6],
              [0,7,4],
              [5,3,2]])
np.sort(x,axis = 1)

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [152]:
np.sort(x,axis = 1)[::-1]

array([[2, 3, 5],
       [0, 4, 7],
       [1, 2, 6]])

In [154]:
np.sort(x,axis = 0)  # 열 단위로 오름차순 정리

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [155]:
np.sort(x,axis = 0)[::-1]  # 열 단위로 내림차순 정리

array([[5, 7, 6],
       [2, 3, 4],
       [0, 1, 2]])

In [156]:
# 튜플 정렬: sorted(튜플, 키)
# 리스트 정렬: 리스트.sort(), sorted(리스트)
# 데이터프레임 정렬: 데이터프레임.sort_values()

In [159]:
# unique
names = np.array(['순신','길동','꺽정','길동','길동'])
np.unique(names)

array(['길동', '꺽정', '순신'], dtype='<U2')

In [161]:
set(names)

{'길동', '꺽정', '순신'}

In [163]:
# in1d(배열1, 배열2): 배열1의 원소가 배열2의 원소를 포함하는지 여부 
np.in1d(names,['순신','꺽정']) 

array([ True, False,  True, False, False])

In [166]:
# 1개의 배열을 바이너리 형식으로 저장 or 바이너리를 읽거나: np.save(), np.load()
x = np.array([0,1,2])
np.save('xsave',x) # x에 저장된 배열을 xsave.npy로 저장

In [169]:
xload = np.load('xsave.npy')
xload


array([0, 1, 2])

In [170]:
# 여러개의 배열을 바이너리 형식으로 저장 or 바이너리를 읽거나: np.savez(), np.load()  (-z는 zip 의미)

In [185]:
x = np.array([0,1,2])
y = np.array([3,4,5])
np.savez('xysavez','x = x, y = y')

In [186]:
xyload = np.load('xysavez.npz')
xyload

In [187]:
xyload['x']

KeyError: 'x is not a file in the archive'

In [188]:
xyload['y']

KeyError: 'y is not a file in the archive'

In [190]:
xyload.close()  # 파일 닫기까지 해줘야 메모리 사용 수월함.

In [194]:
# np.savetxt: 여러개의 배열을 텍스트 파일로 저장
# np.loadtxt: 텍스트 파일을 배열로 불러오기
x = np.array([1,2,3])
y = np.array([4,5,6])
np.savetxt('xytxt.txt', (x,y), fmt = '%.f') # fmt = '%.f' >> 소숫점 제거

In [196]:
xyload = np.loadtxt('xytxt.txt')
xyload

array([[1., 2., 3.],
       [4., 5., 6.]])

In [197]:
# numpy 배열을 여러개로 분할(split)
# hsplit, split: 수평축으로 분할
# vsplit, split: 수직축으로 분할

In [200]:
# 배열을 수평축(열방향)으로 분할
x = np.arange(18).reshape(3,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [202]:
np.hsplit(x,3) # x 배열을 수평축(열방향)으로 3개의 배열로 분할

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [204]:
np.hsplit(x,(2,4)) # x배열을 수평축(열방향)으로 0:2, 2:4, 4:6

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [207]:
np.split(x,3,axis = 1) # axis를 0 또는 1로 주어서 수직축(행방향), 수평축(열방향)으로 나눌 수 있음.

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [209]:
np.split(x,(2,4),axis = 1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [211]:
x1, x2, x3 = np.split(x,(2,4),axis = 1)
x1

array([[ 0,  1],
       [ 6,  7],
       [12, 13]])

In [212]:
x = np.arange(18).reshape(3,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [216]:
np.vsplit(x,3) # 행방향 3개의 배열로 분리
np.vsplit(x,(1,2)) # x[0:1], x[1:2], x[2:3]에서 분할
# x, (1,3,7) -> x[0:1], x[1:3], x[3:7], x[7:10]  (만약 index가 10까지 있다면)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [220]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [222]:
arr[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [223]:
np.flip(arr,axis = 0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [248]:
arr[:,:] # 모든 행과 열 출력

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [250]:
arr[:,::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [252]:
np.flip(arr,axis = 1)

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [254]:
arr[::-1,::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [262]:
np.flip(arr,axis = 0)[:,::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [263]:
np.flip(arr)

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [281]:
a = np.arange(-5,5)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [282]:
# np.where 이용(벡터화 연산으로 속도가 빠르다)
np.where(a>0, a, 0)

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])

In [283]:
# 리스트 컴프리헨션(내포)
[0 if i< 0 else i for i in a] # 기본적으로 for문을 돌리기때문에 속도가 느리다.

[0, 0, 0, 0, 0, 0, 1, 2, 3, 4]

In [284]:
# boolean 참조
a[a<0]  # True인 값들만 나옴


array([-5, -4, -3, -2, -1])

In [285]:
a[a<0] = 0 
a

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])

In [288]:
# 0보다 작으면 0으로 변환, 2보다 크면 2로 변환
np.where(a>2,2,np.where(a<0, 0, a))


array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])

In [291]:
# np.clip(배열, 최솟값 기준, 최댓값기준)
a = np.arange(-5,5)
np.clip(a, 0, 4)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [294]:
np.clip(a, 0, 4, out = a) # 끝에 out을 해주면 출력값이 바뀜.
a


array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])

In [297]:
a=[1,2,3]
np.asarray(a)  # 이미 해당 배열이 있으면 복사하지 않고, 같은 주소를 사용한다.

array([1, 2, 3])

In [302]:
a = [1,2]
b = np.array([1,2])
b

array([1, 2])

In [303]:
b2 = np.asarray(a)
b2

array([1, 2])

In [304]:
b is b2

False

In [306]:
b = np.array([1,21])
np.asarray(b) is b # 주소가 같다.

True

In [307]:
# 단위행렬(항등행렬): 정방행렬 & 대각성분 '1', 나머지 '0'
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [310]:
np.eye(3) # identity와 eye는 같음.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [311]:
# 행렬: 숫자를 사각형으로 나열? 허접한디;;

In [315]:
np.random.choice(5,3)  # arange(5)에서 3개 추출
# 모집단 0~4에서 균등확률분포를 따르는 임의의 수 3개 복원 추출


array([4, 3, 1])

In [317]:
np.random.randint(0,5,3)

array([3, 0, 2])

In [318]:
# 비균등 확률로 표본 복원 추출
p = [0.1, 0.2, 0.2, 0.4, 0.1] # 각 원소별 표본으로 뽑힐 확률
np.random.choice(5,3)

array([4, 1, 3])

In [333]:
np.random.choice(5,3,p=p) # p=표본이 추출될 확률

array([2, 3, 3])

In [339]:
np.random.choice(5,3) # default(replace = True): 복원추출
np.random.choice(5, 3, replace = True)
np.random.choice(5,3, replace = False) # 비복원추출: 나왔던 수는 다시 안나옴(중복없음.)
np.random.choice(5,3, replace = False, p = p)

ValueError: 'a' and 'p' must have same size

In [343]:
fruits = ['apple','banana','lemon','mango']
p = [0.05, 0.05, 0.7, 0.2]
np.random.choice(fruits, 2, p=p, replace = False)

array(['lemon', 'apple'], dtype='<U6')

In [345]:
np.random.seed(1004) # seed를 주면 동일한 데이터 추출 가능.
np.random.choice(5,3)

array([2, 3, 3])

In [346]:
데이터 수집 -> 전처리 -> 분석 -> 모델링 -> 모델 평가 및 개선
          모델? -> 데이터 입력 -> 모델 -> 예측/분류 결과 출력
전체데이터 100개 -> 70개: 모델링 / 30개: 모델평가

ex) 30개 중에서 21개 정답 -> 70% 정확도 모델



SyntaxError: invalid syntax (<ipython-input-346-81608632e8f0>, line 1)

In [351]:
# train / test data 분할 
# 1. 싸이킷-런(머신러닝을 위한 함수의 집합)
x = np.arange(20).reshape(10,2)
y = np.arange(10)
from sklearn.model_selection import train_test_split  # 데이터 나눌 땐 거의 이거 씀.


In [363]:
# x의 1열: 중간고사 등수, 2열: 기말고사 등수
# y: 최종 시험 등수
# 6:4로 train : test data 분할.
xTrain, xTest, yTrain, yTest = train_test_split(x,
                y,
                train_size = 0.7,
                shuffle = True,
                random_state = 1004) # random_state를 줘야 나중에 모델 성능이 나아졌는지 확인이 가능함.
# False로 주면 섞지 않아. True: 섞임.
# x: 수집 데이터 / y: 예측하고자하는 대상
# 데이터가 잘 섞여있어야 알고리즘을 만들고, 테스트할 때 잘 맞는다
# 리스트 4개
# train x data: 모델 만들때 사용되는 x data
# test x data: 모델 평가할 때 사용되는 x data
# train y data: 모델 만들때 사용되는 y data (정답데이터!)
# test y data: 모델 평가할 때 사용되는 y data
# 실제값과 예측값의 차이: error
# 각 예측값들을 합쳐서 평균을 낸 거!! mean sumation error: mse

# xTrain, yTrain  => 모델 만들고
# xTest ==> 모델 ==> 예측/분류 결과 출력
# choice 함수로도 가능함. 근데 코드가 깔끔하니까 굳이 choice 함수를 쓸 필요는 없다.

#### 데이터 -> 모델 -> 예측
#### 모델을 만드는 방법: 알고리즘!

In [365]:
# 브로드캐스팅: shape이 맞지 않는 두 대상의 연산이 가능하도록 하는 기능.
# numpy는 모양이 다른 배열간 연산 불가
# 어떤 조건일 때 모양이 다르더라도 배열간 연산이 가능할까?
a = np.array([1,2,3,4])
b = np.array([1,2])
a+b

TypeError: data type not understood

In [367]:
np.arange(3)+5  # 0, 1, 2(배열) + 5(스칼라)   >>> 배열과 스칼라간의 연산 시 브로드캐스팅 기능 활성화

array([5, 6, 7])

In [369]:
np.arange(11,20).reshape(3,3) + np.arange(3) >>> 

array([[11, 13, 15],
       [14, 16, 18],
       [17, 19, 21]])

In [373]:
np.arange(3).reshape(3,1)  # 3행 1열
np.arange(3) # 1차원 1행 3열
np.arange(3).reshape(3,1) + np.arange(3)  # 3행 3열
#1열 => 3열로 확장               # 1행에서  3행으로 확장됨.
# 차원의 크기가 1일때 브로드캐스팅이 일어날 수 있음.
# 차원의 짝이 맞을 때 브로드캐스팅

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [380]:
arr3d = np.array([[[0,1],[2,3],[4,5],[6,7]],[[8,9],[10,11],[12,13],[14,15]],[[16,17],[18,19],[20,21],[22,23]]])
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [377]:
arr2d = np.arange(0,8).reshape(4,2)
arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [379]:
arr3d + arr2d

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]]])