문제 1.
길이가 10인 0-벡터를 만드세요.

In [37]:
import numpy as np

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

문제 2.
길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [39]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

문제 3.
10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [40]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [41]:
문제 4.
위 벡터의 순서를 바꾸세요.

SyntaxError: invalid syntax (<ipython-input-41-8022487b9fa3>, line 1)

In [42]:
a = np.arange(10,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

문제 5.
0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [43]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

문제 6.
벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [44]:
a = np.array([1,2,0,0,4,0])
a[np.where(a != 0)]

array([1, 2, 4])

문제 7.
3x3 단위 행렬(identity matrix)을 만드세요

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

문제 8.
난수 원소를 가지는 3x3 행렬을 만드세요

In [46]:
arr = np.random.randn(3,3)
arr

array([[-0.46663499, -0.57663557,  1.37443054],
       [-0.03441824, -0.99939941, -0.66837576],
       [ 0.08873001, -0.50172921, -0.3289757 ]])

문제 9.
위에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [47]:
np.max(arr)

1.3744305442120157

In [48]:
np.min(arr)

-0.9993994107255866

문제 10.
위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [49]:
np.mean(arr,axis = 1)

array([ 0.11038666, -0.5673978 , -0.24732496])

In [50]:
np.mean(arr,axis = 0)

array([-0.13744107, -0.69258806,  0.12569303])